// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEiFklTXMpi9LGYtg81I2Y6pob-I7pMNc',
    appId: '1:852943148953:web:a95de21457bda306992508',
    messagingSenderId: '852943148953',
    projectId: 'src-management-c08fe',
    authDomain: 'src-management-c08fe.firebaseapp.com',
    storageBucket: 'src-management-c08fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbi4xTMM_xc-zkwvzH_WtkdhvdM3Vlz2k',
    appId: '1:852943148953:android:177da45c8ccf3043992508',
    messagingSenderId: '852943148953',
    projectId: 'src-management-c08fe',
    storageBucket: 'src-management-c08fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHrJnAbKkNA6-hsvOLQOI8ENXPKJB0tX8',
    appId: '1:852943148953:ios:dc54f2ab3d2dd8cc992508',
    messagingSenderId: '852943148953',
    projectId: 'src-management-c08fe',
    storageBucket: 'src-management-c08fe.appspot.com',
    iosBundleId: 'victor.tran.phan.srcViewer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHrJnAbKkNA6-hsvOLQOI8ENXPKJB0tX8',
    appId: '1:852943148953:ios:427b8eef9f9ad638992508',
    messagingSenderId: '852943148953',
    projectId: 'src-management-c08fe',
    storageBucket: 'src-management-c08fe.appspot.com',
    iosBundleId: 'victor.tran.phan.srcViewer.RunnerTests',
  );
}
